# Walt Yao
# November 2014


INST_MOTOR_MOVE = 0
INST_MOTOR_STEP_IMAGE = 1
INST_MOTOR_STEP = 2
INST_MOTOR_FLASH_IMAGE = 3
INST_MOTOR_STOP = 4
INST_SENSOR_CALIBRATE_IN = 5
INST_SENSOR_CALIBRATE_OUT = 6


INST_MOTOR_MOVE_FRWD = 0
INST_MOTOR_MOVE_BACK = 1

THREAD_TYPE_MAIN_LOOP = 11
THREAD_TYPE_MAIN_ICOM = 12

NUMBER_OF_PRESETS = 20
# NUMBER_ELEMENTS_IN_PRESET = 2

SLAVE_IP1 = '192.168.0.111'
SLAVE_IP2 = '192.168.0.113'
# BROADCAST_IP = '0.0.0.0'
TCP_PORT = 6156
BUFFER_SIZE = 2000

HOME_ROOT = '/home/pi/3d printer/code/scripts'
PRESET_FILENAME = "/home/pi/3d printer/code/scripts/presets.xml"
IMAGE_DIR = "/home/pi/3d printer/test files/images/"
